# Generated by Django 3.1.7 on 2021-04-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Secrecy')])),
                ('unit', models.SmallIntegerField(choices=[(1, '一单元'), (2, '二单元'), (3, '三单元'), (4, '四单元'), (5, '五单元'), (6, '六单元'), (7, '七单元'), (8, '八单元')])),
                ('lesson', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('sounds', models.CharField(max_length=128)),
                ('used_times', models.IntegerField()),
                ('level', models.SmallIntegerField(choices=[(1, '简单'), (2, '容易'), (3, '正常'), (4, '困难'), (5, '极难')])),
                ('add_time', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DictationModel.category')),
            ],
        ),
    ]
