# Generated by Django 3.1.7 on 2021-04-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictationModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='grade',
            field=models.SmallIntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级')]),
        ),
    ]
