# Generated by Django 3.1.5 on 2021-01-23 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='acc_details',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to='TestModel.accountdetails'),
            preserve_default=False,
        ),
    ]
