# Generated by Django 3.1.7 on 2021-03-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookModel', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Secrecy')])),
                ('tel', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='BookModel.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='au_details',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='BookModel.authordetail'),
            preserve_default=False,
        ),
    ]
