# Generated by Django 3.1.7 on 2021-03-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookModel', '0003_auto_20210309_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='au_details',
        ),
        migrations.AddField(
            model_name='authordetail',
            name='author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='BookModel.author'),
            preserve_default=False,
        ),
    ]
