# Generated by Django 3.1.7 on 2021-03-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookModel', '0006_auto_20210316_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authordetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='BookModel.author'),
        ),
    ]
